import React, { useState } from 'react';

import Head from 'next/head'

export default class KeyphraseExtractor extends React.Component {

    constructor(props) {
        super(props);
        this.editor = React.createRef();

        this.process = this.process.bind(this);
    }

    process(e) {
        console.log(this.editor.current.value);
    }

    render() {
        return (
            <div className="w-screen h-screen px-32 py-10 flex flex-col overflow-auto min-w-screen bg-blue-zodiac-900">
                <Head>
                    <title>David Pohl</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main className="w-full h-full">
                    <div className="w-full h-full flex flex-col gap-10">
                        <textarea
                            ref={this.editor}
                            spellCheck="false"
                            id="message"
                            rows="4"
                            class="flex-grow resize-none outline-none font-semibold rounded-lg p-4 bg-darkest-blue text-white"
                        />
                        <div className="flex flex-row justify-center items-center">
                            <button type="button" onClick={this.process} className="text-xl font-bold px-5 py-3 rounded bg-blue-zodiac-800 text-white uppercase transition ease-in-out delay-150 hover:scale-110 hover:bg-blue-zodiac-700 duration-300">process</button>
                        </div>
                    </div>
                </main >
            </div>);
    }

}


