import React, { useState } from 'react';
import Head from 'next/head'


export default function Main() {
    const pages = ["start", "education", "professional", "projects"];

    const [curPage, setCurPage] = useState("start");

    function handleClickPageBullet(e) {
        setCurPage(e.currentTarget.id);
    }

    return (
        <div className="h-screen font-roboto">
            <Head>
                <title>David Pohl</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
            </Head>
            <nav className="fixed h-full px-16 py-6 right-0">
                <div className="relative h-full flex flex-col justify-center items-center">
                    <span className="font-bold absolute top-0 text-3xl text-white tracking-tight">pohl</span>
                    <ul className="space-y-6 flex flex-col items-center">
                        {pages.map((page, i) => (
                            <PageBullet key={i} id={page} onClick={handleClickPageBullet} current={page == curPage} />
                        ))}
                    </ul>
                </div>

            </nav>
            <main className="snap-y snap-mandatory h-screen overflow-auto">
                <section className="snap-start p-64 flex flex-col h-screen bg-dav-darkblue text-white">
                    <h1 className="flex-grow flex items-center text-7xl font-bold tracking-tight">Hi, I'm David.</h1>
                    <p className="flex-grow text-2xl font-semibold tracking-tighter">
                        ...
                    </p>
                </section>





                <section className="snap-start p-64 h-full flex items-center bg-white">
                    <div className="w-full flex flex-col">
                        <div className="flex">
                            <div className="flex flex-col gap-8">
                                <h1 className="text-7xl font-bold text-dav-darkblue tracking-tight">Education</h1>
                                <ol class="relative border-l border-gray-700">
                                    <li class="mb-10 ml-4">
                                        <div class="absolute w-3 h-3 rounded-full mt-1.5 -left-1.5 border border-gray-900 bg-gray-700"></div>
                                        <time class="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">10/2020 - 07/2023</time>
                                        <p class="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">Heidelberg, DE</p>
                                        <h3 class="text-2xl tracking-tight font-semibold text-dav-darkblue">Heidelberg University</h3>
                                        <h4 className="text-lg tracking-tight text-gray-600">BS Computer Science</h4>
                                        <h4 className="tracking-tight text-gray-500 mt-2">GPA: 3.9/4.0</h4>
                                        <h4 className="tracking-tight text-gray-500">FOCUS: Natural Language Processing</h4>
                                        <h4 className="tracking-tight text-gray-500">THESIS: "Approaching Ambiguity in Medical Documents"</h4>
                                    </li>
                                    <li class="mb-10 ml-4">
                                        <div class="absolute w-3 h-3 rounded-full mt-1.5 -left-1.5 border border-gray-900 bg-gray-700"></div>
                                        <time class="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">08/2022 - 12/2022</time>
                                        <p class="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">Raleigh, US</p>
                                        <h3 class="text-2xl tracking-tight font-semibold text-dav-darkblue">NC State University</h3>
                                        <h4 className="text-lg tracking-tight text-gray-600">Exchange Student (Computer Science)</h4>
                                        <h4 className="tracking-tight text-gray-500 mt-2">GPA: 4.0/4.0</h4>
                                        <h4 className="tracking-tight text-gray-500">FOCUS: Frontend Development, Statistics</h4>
                                    </li>
                                    <li class="ml-4">
                                        <div class="absolute w-3 h-3 rounded-full mt-1.5 -left-1.5 border border-gray-900 bg-gray-700"></div>
                                        <time class="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">08/2012 - 06/2020</time>
                                        <p class="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">Cologne, DE</p>
                                        <h3 class="text-2xl tracking-tight font-semibold text-dav-darkblue">Schiller-Gymnasium Cologne</h3>
                                        <h4 className="text-lg tracking-tight text-gray-600">General University Entrance Qualification</h4>
                                        <h4 className="tracking-tight text-gray-500 mt-2">GPA: 3.9/4.0 (Valedictorian)</h4>
                                        <h4 className="tracking-tight text-gray-500">FOCUS: Mathematics, German</h4>
                                    </li>
                                </ol>
                            </div>
                        </div>
                        <div className="flex justify-end">
                            <div className="flex flex-col">
                                <h1 className="text-6xl font-bold text-dav-blue tracking-tight">Education</h1>
                                <p>....</p>
                            </div>
                        </div>
                    </div>
                </section>
                <section className="snap-start p-40 shrink-0 h-screen flex bg-white">
                    <div className="w-full flex flex-col">
                        <h1 className="mb-8 text-6xl tracking-tight font-bold text-dav-purple">Education</h1>
                        <div className="w-full h-full">
                            <div className="flex items-center h-48 gap-8">
                                <div className="flex flex-col justify-between items-center font-semibold text-dav-purple">
                                    <span className="text-xl tracking-tight">OCT</span>
                                    <span className="text-3xl tracking-tight">2020</span>
                                </div>
                                <div className="station flex flex-col bg-dav-purple text-white px-6 py-4 duration-300">
                                    <h1 className="text-4xl font-semibold tracking-tight">Heidelberg University</h1>
                                    <h2 className="text-xl font-medium tracking-tight">B.Sc. Computer Science</h2>
                                </div>
                                <div className="flex flex-col justify-between items-center font-semibold text-dav-purple">
                                    <span className="text-xl tracking-tight">AUG</span>
                                    <span className="text-3xl tracking-tight">2023</span>
                                </div>
                            </div>
                            <div className="flex justify-between items-center h-48 gap-8">
                                <div className="flex flex-col justify-between items-center font-semibold text-dav-purple">
                                    <span className="text-xl tracking-tight">OCT</span>
                                    <span className="text-3xl tracking-tight">2020</span>
                                </div>
                                <div className="flex-grow flex flex-col bg-dav-purple text-white px-6 py-4 rounded">
                                    <h1 className="text-4xl font-semibold tracking-tight">Heidelberg University</h1>
                                    <h2 className="text-xl font-medium tracking-tight">B.Sc. Computer Science</h2>
                                </div>
                                <div className="flex flex-col justify-between items-center font-semibold text-dav-purple">
                                    <span className="text-xl tracking-tight">AUG</span>
                                    <span className="text-3xl tracking-tight">2023</span>
                                </div>
                            </div>
                        </div>



                    </div>
                </section>

            </main>
        </div>
    );
}

function PageBullet(props) {
    return (
        <li>
            <button id={props.id} onClick={props.onClick} className={"nav-bullet" + (props.current ? " current" : "")} />
        </li>
    );
}