import React, { useState } from 'react';
import Head from 'next/head'


export default function Main() {
    const pages = ["start", "education", "professional", "projects"];

    const [curPage, setCurPage] = useState("start");

    function handleClickPageBullet(e) {
        setCurPage(e.currentTarget.id);
    }

    return (
        <div className="h-screen font-open-sans">
            <Head>
                <title>David Pohl</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet"></link>
            </Head>
            <nav className="fixed h-full px-16 py-6 right-0">
                <div className="relative h-full flex flex-col justify-center items-center">
                    <span className="font-bold absolute top-0 text-3xl text-white tracking-tighter">pohl</span>
                    <ul className="space-y-6 flex flex-col items-center">
                        {pages.map((page, i) => (
                            <PageBullet key={i} id={page} onClick={handleClickPageBullet} current={page == curPage} />
                        ))}
                    </ul>
                </div>

            </nav>
            <main className="snap-y snap-mandatory h-screen overflow-auto">
                <section className="snap-start p-40 shrink-0 h-screen flex bg-dav-purple">
                    <div className="">
                        <h1 className="text-7xl font-bold text-white rounded-lg p-1 tracking-tighter">Hi, I'm David.</h1>
                    </div>
                </section>
                <section className="snap-start p-40 shrink-0 h-screen flex bg-white">
                    <div className="w-full flex flex-col">
                        <h1 className="mb-8 text-6xl tracking-tight font-bold text-dav-purple text-end">Education</h1>
                        <div className="w-full h-full">
                            <div className="flex justify-between items-center h-48 gap-8">
                                <div className="flex flex-col justify-between items-center font-semibold text-dav-purple">
                                    <span className="text-xl tracking-tight">OCT</span>
                                    <span className="text-3xl tracking-tight">2020</span>
                                </div>
                                <div className="flex-grow flex flex-col bg-dav-purple text-white px-6 py-4 rounded">
                                    <h1 className="text-4xl font-semibold tracking-tight">Heidelberg University</h1>
                                    <h2 className="text-xl font-medium tracking-tight">B.Sc. Computer Science</h2>
                                </div>
                                <div className="flex flex-col justify-between items-center font-semibold text-dav-purple">
                                    <span className="text-xl tracking-tight">AUG</span>
                                    <span className="text-3xl tracking-tight">2023</span>
                                </div>
                            </div>
                            <div className="flex justify-between items-center h-48 gap-8">
                                <div className="flex flex-col justify-between items-center font-semibold text-dav-purple">
                                    <span className="text-xl tracking-tight">OCT</span>
                                    <span className="text-3xl tracking-tight">2020</span>
                                </div>
                                <div className="flex-grow flex flex-col bg-dav-purple text-white px-6 py-4 rounded">
                                    <h1 className="text-4xl font-semibold tracking-tight">Heidelberg University</h1>
                                    <h2 className="text-xl font-medium tracking-tight">B.Sc. Computer Science</h2>
                                </div>
                                <div className="flex flex-col justify-between items-center font-semibold text-dav-purple">
                                    <span className="text-xl tracking-tight">AUG</span>
                                    <span className="text-3xl tracking-tight">2023</span>
                                </div>
                            </div>
                        </div>



                    </div>
                </section>

            </main>
        </div>
    );
}

function PageBullet(props) {
    return (
        <li>
            <button id={props.id} onClick={props.onClick} className={"nav-bullet" + (props.current ? " current" : "")} />
        </li>
    );
}